name: Preparant per producci贸
run-name: ${{ github.actor }} est pujant l'aplicaci贸 a PROD  
on: [push]
jobs:
  Pujar-a-produccio-amb-SCP:
    runs-on: ubuntu-latest
    steps:
      - name: Obtenint el codi del respositori
        uses: actions/checkout@v4

      - name: Mostrar ubicaci贸n del archivo ESLint
        run: |
          echo 'La ubicaci贸n del archivo ESLint es: $(pwd)/.eslintrc.cjs'

      - name: ESLint
        uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: npm install eslint
      - run: npx eslint .
      
      - name: scp a produccio
        run: |
          echo "${{ secrets.PROD_KEY }}" > ~/prod_key.pem
          chmod 600 ~/prod_key.pem
          cd ${{ github.workspace }}
          echo "Action desplegant a produccio" > ./web/last_deploy.txt
          date >> ./web/last_deploy.txt
          cd ./web/vue-actions/
          npm install
          npm run build
          scp -r -o stricthostkeychecking=no -o UserKnownHostsFile=/dev/null -i "~/prod_key.pem" ./dist/* ${{ secrets.PROD_USER }}@${{ secrets.PROD_HOST }}:/home/a22hugtrigon/web/a22hugtrigonactions.daw.inspedralbes.cat/public_html
          
      - run: echo " This job's status is ${{ job.status }}."潞